### ISSUE TITLE
SafeMode should be SafePrompt

### ISSUE THREAD

**Issue by jcmag** [tghamm/Mistral.SDK#1]
Hi,

I had this error when using your library:

"{\"detail\":[{\"type\":\"extra_forbidden\",\"loc\":[\"body\",\"safe_mode\"],\"msg\":\"Extra inputs are not permitted\",\"input\":false,\"url\":\"https://errors.pydantic.dev/2.5/v/extra_forbidden\"}]}"

and I've fixed it by changing SafeMode to SafePrompt in ChatCompletionRequest.cs :

```
[JsonPropertyName("safe_prompt")]
public bool SafePrompt { get; set; }
```

(see: [https://docs.mistral.ai/api/#operation/createChatCompletion](https://docs.mistral.ai/api/#operation/createChatCompletion))

**Comment by tghamm** [comment]
@jcmag thanks for bringing this to my attention.  There is a new release out that addresses the issue and includes a more comprehensive integration test suite to ensure other parameters are working as expected.

**Comment by jcmag** [comment]
perfect, thanks!
